
#ifndef USD_VERSION_DESCRIPTION
#	define USD_VERSION_DESCRIPTION	""
#endif

#define __USD_VERSION_PRODUCT_STRING_INTERNAL3(s) \
    #s

#define __USD_VERSION_PRODUCT_STRING_INTERNAL2(p, s, b, f) \
	__USD_VERSION_PRODUCT_STRING_INTERNAL3(p.s.b.f)

#define __USD_VERSION_PRODUCT_STRING_INTERNAL(p, s, b, f) \
	__USD_VERSION_PRODUCT_STRING_INTERNAL2(p, s, b, f)

#define USD_VERSION_PRODUCT_STRING	__USD_VERSION_PRODUCT_STRING_INTERNAL(USD_VERSION_MAJOR, USD_VERSION_MINOR, USD_VERSION_REVISION, USD_VERSION_BUILD)
